#!/bin/sh
# This is a generated file; do not edit or check into version control.
export "FLUTTER_ROOT=/Users/muhammadanasshahid/Downloads/flutter-2"
export "FLUTTER_APPLICATION_PATH=/Volumes/ENT/dd1"
export "FLUTTER_TARGET=/Volumes/ENT/dd1/lib/main.dart"
export "FLUTTER_BUILD_DIR=build"
export "SYMROOT=${SOURCE_ROOT}/../build/ios"
export "OTHER_LDFLAGS=$(inherited) -framework Flutter"
export "FLUTTER_FRAMEWORK_DIR=/Users/muhammadanasshahid/Downloads/flutter-2/bin/cache/artifacts/engine/ios"
export "FLUTTER_BUILD_NAME=1.7.0"
export "FLUTTER_BUILD_NUMBER=1.7.0"
export "DART_DEFINES=flutter.inspector.structuredErrors%3Dtrue"
export "DART_OBFUSCATION=false"
export "TRACK_WIDGET_CREATION=true"
export "TREE_SHAKE_ICONS=false"
export "PACKAGE_CONFIG=.packages"
